# Generated by Django 5.1.4 on 2024-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_users_email_4b85f2_idx_and_more"),
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(fields=["zone_name"], name="zones_zone_na_c5113f_idx"),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(fields=["created_at"], name="zones_created_76b4ac_idx"),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(fields=["updated_at"], name="zones_updated_1ad5de_idx"),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(fields=["user_id"], name="zones_user_id_907139_idx"),
        ),
    ]
