# Generated by Django 5.1.4 on 2024-12-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0002_city_cities_city_na_2ea01e_idx_and_more"),
        ("machines", "0002_machine_machines_machine_eb565c_idx_and_more"),
        ("products", "0001_initial"),
        ("users", "0006_user_users_email_4b85f2_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_name"], name="products_product_97a29d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_description"], name="products_product_b815cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_price_fe467e_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["quantity"], name="products_quantit_a80737_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="products_created_e1ba5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["updated_at"], name="products_updated_b2f96c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["user_id"], name="products_user_id_585831_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["city_id"], name="products_city_id_b1b632_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["machine_id"], name="products_machine_f07cd5_idx"
            ),
        ),
    ]
